DROP TABLE IF EXISTS CUSTOMER_USER;  
CREATE TABLE CUSTOMER_USER (  
USER_ID INT AUTO_INCREMENT  PRIMARY KEY,  
USER_NAME VARCHAR(50) NOT NULL,  
USER_PHNUMBER VARCHAR(30) ,
USER_ADDRESS VARCHAR(20),
USER_DESIGNATION VARCHAR(20)
); 

INSERT INTO CUSTOMER_USER VALUES (1,'sivasai','123456789','korukonda','developer');
INSERT INTO CUSTOMER_USER VALUES (2,'lavanya','879239737','vizag','developer');
INSERT INTO CUSTOMER_USER VALUES (3,'bhanu','1232353643','vizag','developer');
INSERT INTO CUSTOMER_USER VALUES (4,'sivakumar','4353534567','rajahmundey','developer');
INSERT INTO CUSTOMER_USER VALUES (5,'surya','8987675773','korukonda','developer');